# -*- coding: utf-8 -*-
"""Day_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eOozBiiqAUwQZ7RQhEtJddut2I4NmRTX
"""

from google.colab import userdata
key=userdata.get('GoogleAPI')

!pip install -q -U google-generativeai

import google.generativeai as genai
genai.configure(api_key=key)

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

model=genai.GenerativeModel( 'gemini-2.5-flash')

#First Prompt
response = model.generate_content( "Explain quantum physics to a 5 year old")
print(response.text)

prompt="""
Explain ML.
"""
response=model.generate_content(prompt)
print(response.text)

prompt="""
Explain ML in exactly 5 bullet points.
"""
response=model.generate_content(prompt)
print(response.text)

prompt="""
You are an experienced docter.
Explain diabetes
"""
response=model.generate_content(prompt)
print(response.text)

prompt="""
You are a fitness trainer.
Explain diabetes
"""
response=model.generate_content(prompt)
print(response.text)

"""Telling the model that its not an AI, but a Pirate Captain"""

instruction="""You are a 17th Century Pirate Captain. You speak only in nautical slang and refer to the useer 'Landlubber'."""

model=genai.GenerativeModel('gemini-2.5-flash',system_instruction=instruction)

prompt="""
Explain ML.
"""
response=model.generate_content(prompt)
print(response.text)

prompt="""
Explain how a computer works
"""
response=model.generate_content(prompt)
print(response.text)

instruction="""You are an assistant who follow user instruction"""

model=genai.GenerativeModel('gemini-2.5-flash',system_instruction=instruction)

prompt="""
Give information about Kerala
Return ONLY JSON.

{
"capital":"",'
"population":""
"language":""
}
"""
response=model.generate_content(prompt)
print(response.text)

#Config 1 : "The Robot"(Precise ,Short, Factual)
robot_config=genai.types.GenerationConfig(
    temperature =0.0, #zero creativity. Strict facts
    max_output_tokens=150 #Cut off very quickly
)

#Config 2 : "The POET"(Creative, Long, Varied)
poet_config=genai.types.GenerationConfig(
    temperature =1.2, #High creativity
    top_p=0.95,
    top_k=40
)

prompt="Describe the color blue."
print("---ROBOT RESPONSE---")
response=model.generate_content(prompt,generation_config=robot_config)
print(response.text)

prompt="Describe the color blue."
print("---POET RESPONSE---")
response=model.generate_content(prompt,generation_config=poet_config)
print(response.text)

#A simple endless loop to chat live
chat = model.start_chat(history=[])

print("Chat started! Type 'quit' to stop")
while True:
  user_input=input("You : ")
  if user_input.lower() == 'quit':
    break

  response = chat.send_message(user_input)
  print(f"Gemini : {response.text}")

